-- 企业门户与客服监控分别保存一份提醒当前状态；reminder_key 在同一业务生命周期内稳定不变，
-- 后续风险阶段通过更新原记录合并，避免仪表盘和客服待办出现重复事项。
CREATE TABLE `saas_enterprise_reminder` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `enterprise_id` bigint NOT NULL COMMENT 'tenant_enterprise.id',
  `reminder_type` varchar(64) NOT NULL COMMENT '提醒类型编码',
  `reminder_key` varchar(200) NOT NULL COMMENT '同一业务提醒生命周期的稳定合并键',
  `reminder_stage` varchar(32) NOT NULL COMMENT '当前提醒阶段',
  `stage_level` int NOT NULL COMMENT '阶段等级，只允许高等级覆盖低等级',
  `severity` varchar(16) NOT NULL COMMENT 'NOTICE WARNING CRITICAL',
  `title` varchar(200) NOT NULL COMMENT '当前阶段标题快照',
  `content` varchar(2000) NOT NULL COMMENT '当前阶段正文快照',
  `business_data_json` json DEFAULT NULL COMMENT '触发时业务数据快照',
  `revision` int NOT NULL DEFAULT 1 COMMENT '有效合并更新版本',
  `trigger_count` int NOT NULL DEFAULT 1 COMMENT '有效触发或升级次数',
  `first_triggered_at` datetime NOT NULL COMMENT '首次触发时间',
  `last_triggered_at` datetime NOT NULL COMMENT '最近有效触发或升级时间',
  `expires_at` datetime DEFAULT NULL COMMENT '不再出现在近期列表的时间',
  `is_read` tinyint NOT NULL DEFAULT 0 COMMENT '企业维度是否已读',
  `read_at` datetime DEFAULT NULL,
  `read_by` bigint DEFAULT NULL COMMENT 'tenant_user.id',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_enterprise_reminder_key` (`enterprise_id`, `reminder_key`),
  KEY `idx_enterprise_reminder_recent` (`enterprise_id`, `severity`, `last_triggered_at`),
  KEY `idx_enterprise_reminder_unread` (`enterprise_id`, `is_read`, `last_triggered_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='企业门户近期提醒';

CREATE TABLE `monitor_enterprise_reminder` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `enterprise_id` bigint NOT NULL COMMENT 'tenant_enterprise.id',
  `enterprise_name_snapshot` varchar(150) NOT NULL COMMENT '触发时企业名称',
  `reminder_type` varchar(64) NOT NULL,
  `reminder_key` varchar(200) NOT NULL COMMENT '与企业提醒一致的合并键',
  `reminder_stage` varchar(32) NOT NULL,
  `stage_level` int NOT NULL,
  `severity` varchar(16) NOT NULL COMMENT 'NOTICE WARNING CRITICAL',
  `title` varchar(200) NOT NULL,
  `content` varchar(2000) NOT NULL,
  `business_data_json` json DEFAULT NULL,
  `revision` int NOT NULL DEFAULT 1 COMMENT '客服处理接口的乐观锁版本',
  `trigger_count` int NOT NULL DEFAULT 1,
  `first_triggered_at` datetime NOT NULL,
  `last_triggered_at` datetime NOT NULL,
  `process_status` tinyint NOT NULL DEFAULT 0 COMMENT '0待处理 1已处理',
  `processed_at` datetime DEFAULT NULL,
  `processed_by` bigint DEFAULT NULL COMMENT 'monitor_user.id',
  `process_remark` varchar(500) DEFAULT NULL,
  `last_processed_at` datetime DEFAULT NULL COMMENT '提醒更新前最近一次处理时间',
  `last_processed_by` bigint DEFAULT NULL,
  `last_process_remark` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_monitor_reminder_key` (`enterprise_id`, `reminder_key`),
  KEY `idx_monitor_reminder_queue` (`process_status`, `severity`, `last_triggered_at`),
  KEY `idx_monitor_reminder_enterprise` (`enterprise_id`, `process_status`, `last_triggered_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客服监控企业提醒';
