spring:
  config:
    activate:
      on-profile: prod

insurance:
  sso:
    saas-exchange-url: ${SAAS_SSO_EXCHANGE_URL:https://www.idatag.com/saasback/internal/sso/exchange}
    portal-authorize-url: ${SAAS_PORTAL_AUTHORIZE_URL:https://www.idatag.com/saasback/internal/sso/portal-authorize}

app:
  cors:
    enabled: false
