spring:
  config:
    activate:
      on-profile: prod

portal:
  sso:
    insurance-frontend-url: ${INSURANCE_FRONTEND_URL:https://www.idatag.com/insurance}
    portal-frontend-url: ${PORTAL_FRONTEND_URL:https://www.idatag.com/saas}

app:
  cors:
    enabled: false
